server:
  port: 8082
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin

app:
  bravo:
    api-key: "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"