version: "3.8"

services:
  mongodb:
    container_name: mongodb
    restart: always
    environment:
      MONGODB_DATABASE: notification_service
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mysqldb:
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "Admin@123$"
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: identity_service
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  neo4jdb:
    container_name: neo4jdb
    restart: always
    volumes:
      - neo4j_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  identity.api:
    container_name: identity.api
    environment:
      - DBMS_CONNECTION=jdbc:mysql://mysqldb:3306/identity_service
    depends_on:
      - mysqldb
    ports:
      - "9080:8080"
    restart: always

  kafka:
    container_name: kafka
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@<your_host>:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER