version: "3.8"

services:
  #database section
  mongodb:
    image: bitnami/mongodb:7.0.11

  mysqldb:
    image: mysql:8.0.36-debian

  neo4jdb:
    image: neo4j:latest

  identity.api:
    image: ${DOCKER_REGISTRY-}identity-service:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: identity-service/Dockerfile
  #  identity.api:
  #    image: huytq3103/identity-service:0.9.0

  kafka:
    image: bitnami/kafka:3.7.0

#network section
networks:
  default:
    name: identity-service-network
    driver: bridge

#volumes sections
volumes:
  mongodb_data:
    name: mongodb_data
  mysql_data:
    name: mysql_data
  neo4j_data:
    name: neo4j_data